spring:
  application.name: ${MG_APP_NAME:backtest}
  datasource:
    url: 'jdbc:postgresql://localhost:63593/backtest'
    password: admin
    username: admin
  security:
    oauth2:
      resourceserver:
        enabled: false
      client:
        enabled: false
  webflux:
    base-path: "/"
  rsocket:
    server:
      mapping-path: /rsocket
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false

MG_SERVER_PORT: 8110
MG_KAFKA_URL: localhost:9092

api:
  url:
    candle: http://localhost:8095/candle

backtest:
  capture:
    enabled-input:
      SPOT_ASK: false
      SPOT_BID: false
      PERP_ASK: false
      PERP_BID: false
      FUND_RATE: false
      CALC_PRFT: false

eureka.client.enabled: false
eureka.client.fetch-registry: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registryFetchIntervalSeconds: 1  # интервал получения регистра (по умолчанию 30)
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1  # интервал обновлений (по умолчанию 30)
    leaseExpirationDurationInSeconds: 1  # время жизни аренды (по умолчанию 90)